project_id                    = "example-project-id-12345"
service_account_id            = "service"
service_account_friendly_name = "Friendly Service's Name"
bucket_name                   = "example-duplicity-backups"
bucket_location               = "us-central1"
storage_class                 = "NEARLINE"
